[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  name = "github.com/golang/mock"
  version = "v1.2.0"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
